---
- hosts: buildservers
  become: true
  vars:
    - warName: sample.war
    - tomcat_version: 8.5.61
    - warRemotePath: /opt/apache-tomcat-{{ tomcat_version }}/webapps
  
  tasks:
   - name: Copy WAR to Remote server
     copy: src={{ warName }} dest={{ warRemotePath }}/{{ warName }} owner=tomcat group=tomcat
